apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.configMapName" . }}
  namespace: {{ include "mysql.namespace" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  init.sql: |
{{ .Values.configMap.initSql | indent 4 }}
