apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" .Chart.Name }}
  namespace: {{ include "mysql.namespace" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
