apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "todoapp.pvcName" . }}
  namespace: {{ include "todoapp.namespace" . }}
  labels:
    {{- include "todoapp.labels" . | nindent 4 }}
spec:
  volumeName: {{ include "todoapp.pvName" . }}
  accessModes:
    {{- toYaml .Values.persistence.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.pvc.requestStorage }}
