apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" .Chart.Name }}
  namespace: {{ include "todoapp.namespace" . }}
  labels:
    {{- include "todoapp.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
