apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "todoapp.serviceAccountName" . }}
  namespace: {{ include "todoapp.namespace" . }}
  labels:
    {{- include "todoapp.labels" . | nindent 4 }}
