apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-%s" .Chart.Name .Values.serviceAccount.name }}
  namespace: {{ include "todoapp.namespace" . }}
  labels:
    {{- include "todoapp.labels" . | nindent 4 }}
